---
- name: Convert2rhel pre-conversion analysis
  hosts: "{{ dynamic_inventory_group | default(omit) }}"
  strategy: ansible.builtin.free
  gather_facts: true
  become: true
  environment:
    CONVERT2RHEL_DISABLE_TELEMETRY: 1
    # CONVERT2RHEL_ALLOW_OLDER_VERSION: 1
    # CONVERT2RHEL_UNSUPPORTED_INCOMPLETE_ROLLBACK: 1
  vars:
    rhsm_username: ""
    rhsm_password: ""
    rhsm_org: "{{ org_id }}"
    rhsm_activation_key: "{{ rhel_lifecycle_environment }}"
    rhsm_activation_key_pre_convert: "{{ rhel_lifecycle_environment }}"
    c2r_include_delay: false
  tasks:
    - name: Verify operating system
      ansible.builtin.assert:
        that:
          - ("ansible_distribution == 'CentOS'") or ("ansible_distribution == 'OracleLinux'")
        fail_msg: "OS must be CentOS or OracleLinux"
        success_msg: "CentOS or OracleLinux requirement met, continue..."

    - name: Verify major and minor versions
      ansible.builtin.assert:
        that:
          - "ansible_distribution_major_version | int  == 7"
          - "ansible_distribution_version.split('.')[1] | int >= 9"
        fail_msg: "Release version must be >= 7.9"
        success_msg: "Release version requirement met, continue..."

    - name: Analyze CentOS 7.9 systems
      when:
        - "ansible_distribution == 'CentOS'"
        - "ansible_distribution_major_version | int  == 7"
        - "ansible_distribution_version.split('.')[1] | int >= 9"
      ansible.builtin.import_tasks: c2r_analysis_centos.yml
    - name: Analyze Oracle Linux 7.9 systems
      when:
        - "ansible_distribution == 'OracleLinux'"
        - "ansible_distribution_major_version | int  == 7"
        - "ansible_distribution_version.split('.')[1] | int >= 9"
      ansible.builtin.import_tasks: c2r_analysis_oracle.yml
    - name: Enable all repositories
      when:
        - "ansible_distribution == 'CentOS'"
        - "ansible_distribution_major_version | int  == 7"
      ansible.builtin.command: |
        yum-config-manager --enable \*
...
