---
- name: Extend logical volume and resize associated filesystem
  hosts: "{{ dynamic_inventory_group | default(omit) }}"
  strategy: free
  gather_facts: true
  become: true
  tasks:
    - name: Extend logical volume 
      community.general.lvol:
        vg: "{{ volume_group_name }}"
        lv: "{{ logical_volume_name }}"
        size: +"{{ extend_logical_volume_mb }}"M
        resizefs: true
...
