---
- name: Remediate
  hosts: "{{ dynamic_inventory_group | default(omit) }}"
  strategy: ansible.builtin.free
  gather_facts: true
  become: true
  force_handlers: true
  tasks:
    - name: Include randomized delay before beginning remediation
      ansible.builtin.command: |
        python3 -c 'import time;import random;zzzzz=random.uniform(15.0,60.0);time.sleep(zzzzz);print(zzzzz)'
      delegate_to: localhost
      connection: local
    - name: "Remediate rhel7 systems"
      when: ansible_distribution_major_version|int == 7
      ansible.builtin.import_tasks: remediate_rhel7.yml
    - name: "Remediate rhel8 systems"
      when: ansible_distribution_major_version|int == 8
      ansible.builtin.import_tasks: remediate_rhel8.yml

  handlers:
    - name: "Restart sshd"
      ansible.builtin.service:
        name: sshd
        state: restarted
    - name: "Restart firewalld"
      ansible.builtin.service:
        name: firewalld
        state: restarted
...
