---
- hosts: "env_{{ lifecycle_stage }}"
  become: yes
  vars:
    check_only: yes
    mountname: "/"

  tasks:
  - name: check operating system
    assert:
      that: "ansible_os_family == 'RedHat'"
      
  - name: Ensure that free space on {{ mountname }} is grater than 20%
    assert:
      that: mount.size_available > mount.size_total|float * 0.2
      msg: disk space has reached 80% threshold
    vars:
      mount: "{{ ansible_mounts | selectattr('mount','equalto',mountname) | list | first }}"
      
  - name: check for updates
    yum:
      name: '*'
      state: latest
      exclude: kernel*
    check_mode: "{{ check_only }}"
    throttle: 1
    register: updates

  - name: output updates dictionary
    debug:
      msg: "{{ updates }}"
      
#  - name: Sending an email using Ansible
#    mail:
#      host: smtp.gmail.com
#      port: 587
#      username: dmeonavneet@gmail.com
#      password: "rbfqhoincpyouxqk"
#      to: 
#      - dmeonavneet@gmail.com
#      - nrathi@redhat.com
#      - rdodia@redhat.com
#      subject: Email By Ansible - about patch 
#      body: Patch Successfuly completed check Satellite server for more details 
#    delegate_to: localhost          
#    run_once: true
#    when: _changed|length > 0
#    vars:
#      _changed: "{{ hostvars|dict2items|
#                      selectattr('value.updates.changed')|
#                      map(attribute='key')|list }}"   
  - name: Template a file to /etc/file.conf
    ansible.builtin.template:
      src: "templates/main.j2"
      dest: index.html
      owner: root
      group: root
      mode: '0644'
    delegate_to: localhost

  - name: Template a file to /etc/file.conf
    ansible.builtin.template:
      src: "templates/patch.j2"
      dest: "{{inventory_hostname}}.html"
      owner: root
      group: root
      mode: '0644'
    delegate_to: localhost

  - name: Create a zip archive of Patch report
    community.general.archive:
      path: "*.html"
      format: zip
      dest: patch_report.zip
    run_once: true
    delegate_to: localhost

  - name: Sending an email using Ansible
    mail:
      host: smtp.gmail.com
      port: 587
      username: dmeonavneet@gmail.com
      password: "rbfqhoincpyouxqk"
      attach:
      - patch_report.zip
      to:
      - dmeonavneet@gmail.com
      - nrathi@redhat.com
      - rdodia@redhat.com
      subject: Email By Ansible - about patch
      body: Patch Successfuly completed check Satellite server for more details
    delegate_to: localhost
    run_once: true



 
  - name: updated package list
    debug:
      msg: "{% if item[0] in packages %}{{ packages[item[0]][0].version }}-{{ packages[item[0]][0].release }}.{{ packages[item[0]][0].arch }} >>> {{ item[1] }} {% else %} {{ item[1] }}{% endif %}"
    loop: "{{ updates.changes.updated }}"
    loop_control:
      label: "{{ item[0] }}"
    when: updates.changes is defined
