---
- hosts: "{{ HOSTS | default('control[0]') }}"
  connection: local
  vars:
    controller_infra_workloads:
      - infra.controller_configuration.execution_environments
      - infra.controller_configuration.projects
      - infra.controller_configuration.inventories
      - infra.controller_configuration.inventory_sources
      - infra.controller_configuration.notification_templates
      - infra.controller_configuration.groups
      - infra.controller_configuration.job_templates
      - infra.controller_configuration.workflow_job_templates
    controller_hostname: "{{ lookup('env', 'TOWER_HOST') }}"
    #controller_hostname: "{{ hostvars[inventory_hostname].ansible_fqdn }}"
    controller_validate_certs: false
  #collections:
  #  - infra.controller_configuration

  tasks:
    - name: Controller deployment instrumentation
      ansible.builtin.uri:
        url: https://docs.google.com/forms/d/e/1FAIpQLSdIZ77YpETjEfGOoYlXtMnQiU-6M7QFlb2hJA4ujo25QYb2jw/formResponse
        method: POST
        body: "ifq&entry.1569353616=satellite &entry.498055740={{ lookup('ansible.builtin.env', 'AWX_HOST') }}&sumbit=Submit"
      ignore_errors: true

    - name: Slurp dynamic_development_source_vars.yaml
      ansible.builtin.slurp: src=files/dynamic_development_source_vars.yaml
      register: dynamic_development_source_vars_slurped

    - ansible.builtin.set_fact:
        dynamic_development_source_vars: "{{ dynamic_development_source_vars_slurped['content'] | b64decode }}"

    # Gather EC2 metadata facts
    - amazon.aws.ec2_metadata_facts:
  
    - ansible.builtin.set_fact:
        workshop_ec2_region: "{{ ansible_ec2_instance_identity_document_region }}"

    - ansible.builtin.debug:
        msg: "{{ dynamic_development_source_vars }}"

    - name: Include CentOS to RHEL lifecycle_environments vars
      ansible.builtin.include_vars:
        file: config_as_code/satellite/centos7_c2r/lifecycle_environments.yml
      delegate_to: satellite.example.com

# Allow projects to pull collections via collections/requirements.yml
    - name: Turn on AWX_COLLECTIONS_ENABLED on controller
      awx.awx.settings:
        name: AWX_COLLECTIONS_ENABLED
        value: true
        controller_host: "{{ lookup('env', 'TOWER_HOST') }}"
        validate_certs: false

    - name: Call dispatch role
      ansible.builtin.include_role:
        name: infra.controller_configuration.dispatch
...
